# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dasom Lee
title: Statistics PhD candidate in North Carolina State University
email: idasomm@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  idasomm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: dasom-lee
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Dasom Lee, it's like  <mark>D_awesome</mark>!


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/idasomm
        # link_text: Project Website
        additional_links:
          - title:  idasomm/DACWsurvival
            icon: fab fa-github
            url: github.com/idasomm/DACWsurviva
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          
        description: | # this will include new lines to allow paragraphs
          hahaha
        
        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: United Therapeutics
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Biostatistics Fellow
        caption: May 2019 - May 2020, Aug 2020 - present
        description: | # this will include new lines to allow paragraphs
          Biostatistics Fellow

      - title: Genentech
        sub_title: Biostatistics Intern
        caption: May 2020 - Aug 2020
        description: | # this will include new lines to allow paragraphs
          I love San Francisco (tho haven't been there lol :-< )
          
          
          
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: North Carolina State University
        bold: PhD in Statistics
        caption: PhD in Statistics (Expected graduation May 2022)
        #sub_title: 
        #description: | # this will include new lines to allow paragraphs
        #  Haha Ph.D candidate! Want to graduate!!!!!

      - layout: top-middle
        title: Korea University
        bold: MS in Statistics
        sub_title: MS in Statistics (Feb. 2017)

      - layout: left
        title: Korea University
        caption: Feb. 2015
        sub_title: BS in Statistics
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Tennis
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-tactile
